---  # Resolve Project Exporter configuration

app:
  loglevel: WARNING
  log_to_file: false
  logfile_path: R:/Resolve Project Backups/@logs

schedule:
  countdown_warning: 30 # Set to 0 for no countdown warning
  enabled_backup_music: true
  backup_music_path: R:/Resolve Project Backups/backup_song.mp3

export:
  archive_in_project_dir: true
  archive_in_static_dir: false
  archive_static_dir: R:/Resolve Project Backups 
